language: ruby
rvm:
  - 2.4.1
sudo: false
script: bundle exec rake test
before_script:
  - gem install bundler
  - psql -c 'create database active_median_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
